CONTIGS=${2}
BINNER1_CONTIG2BIN=${3}
BINNER2_CONTIG2BIN=${4}
BINNER3_CONTIG2BIN=${5}
OUT=${1}/

CMD="DAS_Tool -i ${BINNER1_CONTIG2BIN},${BINNER2_CONTIG2BIN},${BINNER3_CONTIG2BIN} -l "BINNER1","BINNER2","BINNER3" -c ${CONTIGS} -o ${OUT} --write_bins"
echo "Running the following command: ${CMD}"

eval $CMD


